config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts, only: [:new, :create, :index]
  root to: 'users#index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  before_create :generate_token

  validates :username, presence: true
  validates :email, presence: true
  validates :password_digest, presence: true

  has_secure_password

  def generate_token
    token_generated = SecureRandom.urlsafe_base64
    token_encrypted = Digest::SHA1.hexdigest(token_generated.to_s)
    self.login_token = token_encrypted
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def find_user
    @user ||= User.find_by(:login_token => cookies.permanent[:login_token])
  end

  def signed_in
    find_user
    if @user.nil?
      flash[:danger] = "You need to login first"
      redirect_to login_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in , only: [:new, :create]

  def post_params
    params.require(:post).permit(:username, :title, :content)
  end

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "Post created"
      redirect_to posts_path
    else
      flash.now[:danger] = "Something went wrong, please repeat the process"
      render :new
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    my_user = User.find_by(:username => params[:session][:username])
    if my_user && my_user.authenticate(params[:session][:password])
      flash[:success] = "success!"
      cookies.permanent[:login_token] = my_user.login_token
      redirect_to users_path
    else
      flash.now[:danger] = "failed!"
      render :new
    end
  end

  def destroy
    find_user
    if @user.nil?
      flash[:danger] = "Not signed in"
    else
      cookies.permanent[:login_token] = nil
      flash[:success] = "Signed out"
    end
    redirect_to users_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def find_user
    @user ||= User.find_by(:login_token => cookies.permanent[:login_token])
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1> All posts</h1>

<% find_user %>
<% @posts.each do |post| %>
  <br>
  Title = <%= post.title %> <br>
  Author =
    <% if @user.nil? %>
      <%= "Censored" %> <br>
    <% else %>
      <%= post.username %> <br>
    <% end %>
    Content = <%= post.content %> <br>
  <br>
<% end %>
<% if !@user.nil? %>
  <%= link_to "Make new one", new_post_path %> <br>
<% end %>

<%= link_to "<< Back to Home", users_path %>

app/views/posts/new.html.erb
<h1> Make New Post </h1>

<%= form_for @post do |f| %>
  <%= f.text_field :title %><br>
  <%= f.text_area :content %> <br>
  <%= f.hidden_field :username, value: @user[:username]%>
  <%= f.submit "Post this!" %> <br>
<% end %>

app/views/users/index.html.erb
<h1> Welcome to members-only! </h1>

<%= link_to "See All Posts", posts_path %>
<%= link_to "Login", login_path %>
<%= link_to "Logout", logout_path, method: :delete, data: {confirm: "Really sign out?"}%>